Repository pingcap/tidb-tools, pull requests merged in 2018-12, with the labels that each got.

#141 sync_diff_inspector: fix a misleading regex example in config.toml
  sync_diff_inspector/config.toml
Labels: status/LGTM2, unimportant

#146 watcher: move watcher from tidb-enterprise-tools
  pkg/watcher/event.go
  pkg/watcher/watcher.go
  pkg/watcher/watcher_test.go
Labels: priority/normal, status/LGT2, type/feature

#150 use old version pd, and remove ddl checker temporary
  Makefile
  README.md
  ddl_checker/README.md
  ddl_checker/main.go
  dump_region/main.go
  go.mod1
  go.sum1
  pkg/ddl-checker/ddl_syncer.go
  pkg/ddl-checker/executable_checker.go
  pkg/ddl-checker/executable_checker_test.go
  tidb-binlog/binlogctl/meta.go
  tidb-binlog/pump_client/client.go
Labels: priority/normal, status/LGT2, type/compatibility

#152 update errors pkg
  go.mod1
  go.sum1
  importer/config.go
  importer/main.go
  pkg/binlog-filter/filter.go
  pkg/check/privilege.go
  pkg/check/table_structure.go
  pkg/check/util.go
  pkg/column-mapping/column.go
  pkg/dbutil/common.go
  pkg/dbutil/index.go
  pkg/dbutil/query.go
  pkg/dbutil/table.go
  pkg/dbutil/variable.go
  pkg/diff/chunk.go
  pkg/diff/diff.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/importer/db.go
  pkg/importer/job.go
  pkg/importer/parser.go
  pkg/table-router/router.go
  pkg/table-rule-selector/trie_selector.go
  pkg/utils/errors.go
  pkg/utils/security.go
  pkg/utils/urls.go
  sync_diff_inspector/config.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  tidb-binlog/binlogctl/config.go
  tidb-binlog/binlogctl/main.go
  tidb-binlog/binlogctl/meta.go
  tidb-binlog/binlogctl/nodes.go
  tidb-binlog/driver/reader/offset.go
  tidb-binlog/driver/reader/reader.go
  tidb-binlog/node/registry.go
  tidb-binlog/pump_client/client.go
  tidb-binlog/pump_client/client_test.go
  tidb-binlog/pump_client/pump.go
Labels: priority/unimportant, status/PTAL, type/update-package

#151 *: add examples for features and case scenarios
  docs/dm/zh_CN/README.md
  docs/dm/zh_CN/features/binlog-filter.md
  docs/dm/zh_CN/features/black-white-list.md
  docs/dm/zh_CN/features/column-mapping.md
  docs/dm/zh_CN/features/table-route.md
  docs/dm/zh_CN/features/table-selector.md
  docs/dm/zh_CN/get-started.md
  docs/dm/zh_CN/maintenance/dm-ansible.md
  docs/dm/zh_CN/overview.md
  docs/dm/zh_CN/precheck.md
  docs/dm/zh_CN/restrictions.md
  docs/dm/zh_CN/task-handling/task-commands.md
  docs/dm/zh_CN/use-cases/one-tidb-slave.md
  docs/dm/zh_CN/use-cases/shard-merge.md
Labels: priority/normal, status/LGT2, type/enhancement

#153 docs: add introduction of query-status and relay-log feature
  docs/dm/zh_CN/README.md
  docs/dm/zh_CN/features/relay-log.md
  docs/dm/zh_CN/maintenance/query-status.md
Labels: priority/normal, status/LGT1, type/enhancement

#142 update pkg about database
  pkg/dbutil/common.go
  pkg/dbutil/common_test.go
  pkg/dbutil/index.go
  pkg/dbutil/index_test.go
  pkg/dbutil/table_test.go
  pkg/dbutil/types.go
  pkg/diff/chunk.go
  pkg/utils/util.go
Labels: priority/normal, status/LGT2, type/feature

#155 update dm docs index
  docs/dm/zh_CN/README.md
  docs/dm/zh_CN/overview.md
  docs/dm/zh_CN/task-handling/query-status.md
Labels: priority/normal, status/LGT2, type/enhancement
