Repository pingcap/tidb-tools, pull requests merged in 2019-02, with the labels that each got.

#197 diff: can use multiple columns to split chunks
  pkg/dbutil/common.go
  pkg/dbutil/common_test.go
  pkg/dbutil/index.go
  pkg/dbutil/index_test.go
  pkg/dbutil/table_test.go
  pkg/dbutil/types.go
  pkg/diff/chunk.go
  pkg/diff/chunk_test.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/diff/merge.go
  pkg/diff/util.go
  pkg/utils/util.go
  sync_diff_inspector/config.go
  sync_diff_inspector/config.toml
  sync_diff_inspector/diff.go
Labels: priority/normal, status/LGT2, type/cherry-pick

#198 driver/reader: return the next offset instead of sarama.OffsetNewest
  tidb-binlog/driver/reader/offset.go
  tidb-binlog/driver/reader/offset_test.go
Labels: status/LGT2, type/bug-fix

#192 DM: refine column restriction in column-mapping
  docs/dm/zh_CN/features/column-mapping.md
Labels: priority/normal, status/LGT1, type/enhancement

#195 diff: get table info before check
  pkg/diff/chunk.go
  pkg/diff/diff.go
Labels: priority/important, qa, status/LGT2, type/bug-fix

#199 run make fmt
  ddl_checker/main.go
  pkg/ddl-checker/ddl_syncer.go
  pkg/ddl-checker/executable_checker.go
  pkg/ddl-checker/executable_checker_test.go
  pkg/diff/chunk.go
  pkg/utils/urls_test.go
Labels: priority/unimportant, status/LGT2, type/typo

#201 docs: add "阿里云 RDS 支持限制"
  docs/dm/zh_CN/README.md
  docs/dm/zh_CN/vendors/aliyun-rds.md
Labels: priority/normal, status/LGT2, type/doc

#200 some minor update on dm's doc
  docs/dm/zh_CN/change-log.md
  docs/dm/zh_CN/data-interaction-details.md
  docs/dm/zh_CN/get-started.md
  docs/dm/zh_CN/maintenance/dm-ansible.md
  docs/dm/zh_CN/maintenance/dm-migrate.md
  docs/dm/zh_CN/precheck.md
  docs/dm/zh_CN/shard-table/handle-DDL-lock.md
  docs/dm/zh_CN/task-handling/dmctl-manual.md
Labels: priority/unimportant, status/LGT2, type/doc

#203 pick driver/reader: return the next offset instead of sarama.OffsetNewest
  tidb-binlog/driver/reader/offset.go
  tidb-binlog/driver/reader/offset_test.go
Labels: status/LGT2, type/cherry-pick

#160 diff: refine code && add unit test for sharding tables
  pkg/dbutil/common.go
  pkg/dbutil/index.go
  pkg/dbutil/query.go
  pkg/diff/chunk.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/diff/merge.go
  pkg/diff/merge_test.go
  sync_diff_inspector/diff.go
Labels: priority/normal, qa, status/LGT1, type/enhancement, type/test

#205 diff: refine code && add unit test for sharding tables
  pkg/dbutil/common.go
  pkg/dbutil/index.go
  pkg/dbutil/query.go
  pkg/diff/chunk.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/diff/merge.go
  pkg/diff/merge_test.go
  sync_diff_inspector/diff.go
Labels: priority/normal, status/LGT2, type/cherry-pick

#206 diff: minor fix on compare data
  pkg/diff/diff.go
  pkg/diff/diff_test.go
Labels: priority/normal, status/LGT2, type/bug-fix

#207 diff: minor fix on compare data (#206)
  pkg/diff/diff.go
Labels: priority/normal, status/LGT2, type/cherry-pick
