Repository pingcap/tidb-tools, pull requests merged in 2019-06, with the labels that each got.

#240 diff: remove use-rowid config
  pkg/dbutil/common.go
  pkg/dbutil/table.go
  pkg/diff/README.md
  pkg/diff/chunk_test.go
  pkg/diff/diff.go
  sync_diff_inspector/README.md
  sync_diff_inspector/config.go
  sync_diff_inspector/config.toml
  sync_diff_inspector/config_sharding.toml
  sync_diff_inspector/diff.go
Labels: status/LGT1

#245 diff: update column's length for checkpoint table
  pkg/diff/checkpoint.go
Labels: priority/unimportant, status/LGT2

#239 diff: add integration test
  Makefile
  tests/README.md
  tests/_utils/check_contains
  tests/_utils/check_db_status
  tests/importer/run.sh
  tests/run.sh
  tests/sync_diff_inspector/config_base.toml
  tests/sync_diff_inspector/run.sh
  tests/sync_diff_inspector/shard/config.toml
  tests/sync_diff_inspector/shard/run.sh
  tests/sync_diff_inspector/snapshot/run.sh
  tests/util.sh
Labels: priority/normal, status/LGT2, type/test

#250 diff: fix num is nil
  pkg/diff/merge.go
  pkg/diff/merge_test.go
Labels: priority/normal, status/LGT2, type/bug-fix

#252 pkg: use case insensitive event in binlog filter
  pkg/binlog-filter/filter.go
  pkg/binlog-filter/filter_test.go
Labels: status/LGT2, type/enhancement
