Repository pingcap/tidb-tools, pull requests merged in 2019-04, with the labels that each got.

#215 diff: add config to only use checksum, skip select data
  pkg/diff/diff.go
  sync_diff_inspector/config.go
  sync_diff_inspector/config.toml
  sync_diff_inspector/diff.go
Labels: priority/normal, status/LGT2, type/feature

#225 pump client: add bench mark test
  tidb-binlog/pump_client/bench_test.go
  tidb-binlog/pump_client/client_test.go
Labels: type/test

#224 sync-diff-inspector: support checkpoint
  go.mod1
  go.sum1
  pkg/dbutil/common.go
  pkg/dbutil/common_test.go
  pkg/diff/checkpoint.go
  pkg/diff/checkpoint_test.go
  pkg/diff/chunk.go
  pkg/diff/chunk_test.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/diff/spliter_test.go
  pkg/diff/util.go
  pkg/utils/errors_test.go
  sync_diff_inspector/config.go
  sync_diff_inspector/config.toml
  sync_diff_inspector/diff.go
  tidb-binlog/pump_client/client.go
  tidb-binlog/pump_client/pump.go
Labels: priority/important, status/LGT2, type/feature

#226 diff: add config to only use checksum, skip select data (#215)
  pkg/diff/diff.go
  sync_diff_inspector/config.go
  sync_diff_inspector/config.toml
  sync_diff_inspector/diff.go
Labels: priority/normal, status/LGT2, type/cherry-pick

#228 pkg/dbutil: Add function GetViews
  pkg/dbutil/common.go
Labels: status/PTAL

#229 pump_client: Cleanups
  tidb-binlog/pump_client/client.go
  tidb-binlog/pump_client/pump.go
  tidb-binlog/pump_client/selector.go
Labels: status/LGT2

#232 Fix typo in comment
  tidb-binlog/slave_binlog_proto/go-binlog/binlog.pb.go
  tidb-binlog/slave_binlog_proto/proto/binlog.proto
Labels: status/LGT2

#230 pump_client: Use `CommitTS % numberOfPumps` instead of hashing
  tidb-binlog/pump_client/selector.go
Labels: status/LGT2, type/enhancement

#231 diff: judge whether column exist when sort data
  pkg/diff/diff.go
  pkg/diff/merge.go
  pkg/diff/util.go
  pkg/diff/util_test.go
Labels: priority/unimportant, status/LGT2, type/bug-fix

#227 sync-diff-inspector: support checkpoint
  checker/main.go
  go.mod1
  go.sum1
  importer/main.go
  pkg/dbutil/common.go
  pkg/dbutil/common_test.go
  pkg/ddl-checker/executable_checker.go
  pkg/diff/checkpoint.go
  pkg/diff/checkpoint_test.go
  pkg/diff/chunk.go
  pkg/diff/chunk_test.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/diff/merge.go
  pkg/diff/spliter_test.go
  pkg/diff/util.go
  pkg/importer/db.go
  pkg/importer/importer.go
  pkg/importer/job.go
  pkg/importer/parser.go
  pkg/utils/errors_test.go
  sync_diff_inspector/config.go
  sync_diff_inspector/config.toml
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  tidb-binlog/binlogctl/main.go
  tidb-binlog/binlogctl/meta.go
  tidb-binlog/binlogctl/nodes.go
  tidb-binlog/driver/example/mysql/mysql.go
  tidb-binlog/driver/example/print/print.go
  tidb-binlog/driver/reader/offset.go
  tidb-binlog/driver/reader/reader.go
  tidb-binlog/node/node.go
  tidb-binlog/node/registry.go
  tidb-binlog/pump_client/client.go
  tidb-binlog/pump_client/pump.go
  tidb-binlog/pump_client/selector.go
Labels: priority/important, status/LGT2, type/cherry-pick

#235 *: add clean in Makefile && sync log for all tools
  Makefile
  ddl_checker/main.go
  dump_region/main.go
  go.sum1
  importer/main.go
  pkg/utils/util.go
  sync_diff_inspector/main.go
  tidb-binlog/binlogctl/main.go
Labels: priority/unimportant, status/LGT2
