Repository pingcap/tidb-tools, pull requests merged in 2019-03, with the labels that each got.

#208 binlog: add test for node registry
  tidb-binlog/node/node.go
  tidb-binlog/node/registry.go
  tidb-binlog/node/registry_test.go
Labels: duplicate, priority/normal, status/LGT2, type/test

#212 refine name of shard table checker
  pkg/check/table_structure.go
Labels: status/LGT1

#209 diff: add unit test for chunk split
  Makefile
  go.mod1
  go.sum1
  pkg/dbutil/common.go
  pkg/diff/chunk.go
  pkg/diff/chunk_test.go
  pkg/diff/diff_test.go
  pkg/diff/merge_test.go
  pkg/diff/spliter_test.go
Labels: priority/normal, status/LGT2, type/test

#216 diff: add unit test for chunk split (#209)
  Makefile
  go.mod1
  go.sum1
  pkg/dbutil/common.go
  pkg/diff/chunk.go
  pkg/diff/chunk_test.go
  pkg/diff/diff_test.go
  pkg/diff/merge_test.go
  pkg/diff/spliter_test.go
Labels: status/LGT2, type/cherry-pick

#217 update log to pingcap/log
  Makefile
  go.mod1
  go.sum1
  importer/main.go
  pkg/dbutil/common.go
  pkg/ddl-checker/executable_checker.go
  pkg/diff/chunk.go
  pkg/diff/diff.go
  pkg/diff/merge.go
  pkg/diff/util.go
  pkg/importer/db.go
  pkg/importer/importer.go
  pkg/importer/job.go
  pkg/importer/parser.go
  sync_diff_inspector/config.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  tidb-binlog/binlogctl/main.go
  tidb-binlog/binlogctl/meta.go
  tidb-binlog/binlogctl/nodes.go
  tidb-binlog/driver/example/mysql/mysql.go
  tidb-binlog/driver/example/print/print.go
  tidb-binlog/driver/reader/offset.go
  tidb-binlog/driver/reader/reader.go
  tidb-binlog/node/node.go
  tidb-binlog/node/registry.go
  tidb-binlog/pump_client/client.go
  tidb-binlog/pump_client/pump.go
  tidb-binlog/pump_client/selector.go
Labels: priority/normal, status/LGT2, type/log

#221 pump client: support change select pump's strategy
  tidb-binlog/pump_client/client.go
  tidb-binlog/pump_client/client_test.go
  tidb-binlog/pump_client/selector.go
Labels: priority/normal, status/LGT2, type/feature

#223 pump client: add compatible with kafka version && refine retry && add strategy config
  checker/main.go
  dump_region/main.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/watcher/event.go
  pkg/watcher/watcher.go
  pkg/watcher/watcher_test.go
  tidb-binlog/binlogctl/meta.go
  tidb-binlog/binlogctl/nodes.go
  tidb-binlog/node/registry.go
  tidb-binlog/pump_client/client.go
  tidb-binlog/pump_client/client_test.go
  tidb-binlog/pump_client/pump.go
  tidb-binlog/pump_client/selector.go
Labels: status/LGT2, type/cherry-pick
