Repository pingcap/tidb-tools, pull requests merged in 2019-09, with the labels that each got.

#264 consume and parse kafka binlog message for java demo
  tidb-binlog/driver/example/kafkaReader/.gitignore
  tidb-binlog/driver/example/kafkaReader/README.md
  tidb-binlog/driver/example/kafkaReader/pom.xml
  tidb-binlog/driver/example/kafkaReader/src/main/java/Booter.java
  tidb-binlog/driver/example/kafkaReader/src/main/java/com/pingcap/kafkareader/proto/BinLogInfo.java
  tidb-binlog/driver/example/kafkaReader/src/main/java/com/pingcap/kafkareader/proto/DescriptorProtos.java
  tidb-binlog/driver/example/kafkaReader/src/main/java/com/pingcap/kafkareader/proto/GoGoProtos.java
  tidb-binlog/driver/example/kafkaReader/src/main/resources/proto/binlog.proto
  tidb-binlog/driver/example/kafkaReader/src/main/resources/proto/descriptor.proto
  tidb-binlog/driver/example/kafkaReader/src/main/resources/proto/gogo.proto
Labels: Contributor, priority/normal, status/LGT2, status/PTAL, type/feature

#266 remove binlogctl
  Makefile
  README.md
  tidb-binlog/binlogctl/README.md
  tidb-binlog/binlogctl/config.go
  tidb-binlog/binlogctl/main.go
  tidb-binlog/binlogctl/meta.go
  tidb-binlog/binlogctl/nodes.go
Labels: priority/unimportant, status/LGT2

#267 column mapping: update readme
  pkg/column-mapping/README.md
Labels: priority/unimportant, status/LGT2, type/doc

#271 check: update instruction for auto-increment key checking
  pkg/check/table_structure.go
Labels: priority/unimportant, status/LGT1

#273 filter: return error if passed invalid regex pattern
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: status/LGT2, type/enhancement
