Repository pingcap/tidb-tools, pull requests merged in 2019-07, with the labels that each got.

#254 Fix: watcher's modify event condition won't trigger on macOS
  pkg/watcher/watcher.go
Labels: priority/normal, status/LGT2, type/bug-fix

#255 refine reader.go to avoid message blocking
  tidb-binlog/driver/reader/reader.go
Labels: status/LGT1, status/WIP

#249 diff: remove tidb-instance-id config and find tidb instance automatic
  sync_diff_inspector/config.go
  sync_diff_inspector/config.toml
  sync_diff_inspector/diff.go
  tests/_utils/check_not_contains
  tests/sync_diff_inspector/config_base.toml
  tests/sync_diff_inspector/run.sh
Labels: status/LGT2, status/PTAL, type/test

#246 diff: optimize configuration file structure
  sync_diff_inspector/README.md
  sync_diff_inspector/config.toml
  sync_diff_inspector/config_sharding.toml
Labels: priority/unimportant, status/LGT2

#257 check: support verify grant without password
  pkg/check/privilege.go
  pkg/check/privilege_test.go
Labels: status/LGT1, type/enhancement
