Repository pingcap/tidb-tools, pull requests merged in 2019-11, with the labels that each got.

#279 restore-util: wait for scatter region sequentially
  pkg/restore-util/client.go
  pkg/restore-util/split.go
Labels: status/LGT2

#281 restore-util: add on split hook
  pkg/restore-util/split.go
  pkg/restore-util/split_test.go
Labels: status/LGT1

#282 *: replace coreos/etcd with etcdio/etcd
  go.mod1
  go.sum1
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/hack/hack.go
  tidb-binlog/node/registry.go
  tidb-binlog/node/registry_test.go
  tidb-binlog/pump_client/client.go
Labels: status/LGT2

#284 update tidb
  Makefile
  go.mod1
  go.sum1
  pkg/importer/parser.go
Labels: status/LGT2

#283 restore-util: fix returned new region is nil
  pkg/restore-util/client.go
  pkg/restore-util/split.go
Labels: status/LGT2

#280 diff: add sql-mode config
  pkg/check/table_structure.go
  pkg/dbutil/common.go
  pkg/dbutil/common_test.go
  pkg/dbutil/index_test.go
  pkg/dbutil/table.go
  pkg/dbutil/table_test.go
  pkg/diff/chunk_test.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/diff/merge_test.go
  pkg/diff/spliter_test.go
  pkg/diff/util_test.go
  sync_diff_inspector/diff.go
  tests/sync_diff_inspector/snapshot/run.sh
Labels: already-update-docs, priority/normal, status/LGT2, type/feature

#276 check/table_structure: fix typo
  pkg/check/table_structure.go
Labels: priority/unimportant, status/PTAL, type/typo

#286 pkg/etcd: return revision when create key
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  tidb-binlog/node/registry.go
Labels: priority/unimportant, status/LGT2

#288 open sarama error and update sarama read timeout
  go.mod1
  go.sum1
  tidb-binlog/driver/reader/offset.go
  tidb-binlog/driver/reader/reader.go
Labels: status/LGT2

#289 use common kafka config in reader
  tidb-binlog/driver/reader/reader.go
Labels: status/LGT2

#291 Add buf size config
  tidb-binlog/driver/reader/reader.go
Labels: status/LGT1

#293 restore-util: fix overlapped error message
  pkg/restore-util/range.go
  pkg/restore-util/range_test.go
  pkg/restore-util/split.go
Labels: status/LGT1

#294 pkg/etcd: add function to get etcd client
  pkg/etcd/etcd.go
Labels: priority/unimportant, status/LGT1, status/LGT2

#295 refine some errors' message
  pkg/check/util.go
  pkg/column-mapping/column.go
  pkg/dbutil/common.go
  pkg/table-router/router.go
Labels: status/LGT2
