Repository pingcap/tidb-tools, pull requests merged in 2019-08, with the labels that each got.

#260 pump_client: bugfixes
  tidb-binlog/pump_client/client.go
  tidb-binlog/pump_client/pump.go
  tidb-binlog/pump_client/selector.go
Labels: status/LGT1, type/bug-fix

#259 diff: update column's type in checkpoint table
  pkg/diff/checkpoint.go
Labels: priority/normal, status/LGT2, status/PTAL

#248 diff: update ignore-column config && add integration test
  pkg/dbutil/common.go
  pkg/diff/README.md
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/diff/util.go
  pkg/diff/util_test.go
  sync_diff_inspector/config.go
  sync_diff_inspector/config.toml
  sync_diff_inspector/diff.go
  sync_diff_inspector/util.go
  tests/sync_diff_inspector/ignore_column/config.toml
  tests/sync_diff_inspector/ignore_column/run.sh
Labels: priority/normal, status/LGT2, type/bug-fix, type/test

#258 diff: clean checkpoint info in several times to avoid `transaction is too large` error in TiDB
  pkg/dbutil/common.go
  pkg/dbutil/common_test.go
  pkg/diff/checkpoint.go
  pkg/diff/diff.go
Labels: priority/normal, status/LGT1, type/bug-fix
