Repository pingcap/tidb-tools, pull requests merged in 2019-05, with the labels that each got.

#237 diff: add connection manage
  ddl_checker/main.go
  dump_region/main.go
  importer/main.go
  pkg/dbutil/common.go
  pkg/diff/checkpoint_test.go
  pkg/diff/chunk.go
  pkg/diff/chunk_test.go
  pkg/diff/conn.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/diff/util.go
  pkg/diff/util_test.go
  pkg/utils/util.go
  sync_diff_inspector/config.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  tidb-binlog/binlogctl/main.go
Labels: priority/important, status/LGT2, type/bug-fix

#236 column-mapping: set schemaID/tableID to 0 if numeric suffix is missing
  pkg/column-mapping/README.md
  pkg/column-mapping/column.go
  pkg/column-mapping/column_test.go
Labels: priority/normal, status/LGT2, type/feature

#242 diff: some minor fix
  pkg/dbutil/table.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/diff/util.go
  pkg/diff/util_test.go
Labels: status/LGT1, type/bug-fix
