Repository pingcap/tidb-tools, pull requests merged in 2019-01, with the labels that each got.

#157 pkg: add windows cpu utils support
  pkg/utils/cpu_posix.go
  pkg/utils/cpu_windows.go
Labels: status/LGT2, type/enhancement

#159 *: support global sql-pattern filter
  pkg/binlog-filter/filter_test.go
  pkg/table-rule-selector/trie_selector.go
Labels: priority/normal, status/LGT2, type/enhancement

#154 [DNM]docs: refine sql exception operation
  docs/dm/zh_CN/troubleshoot/skip-replace-sqls.md
Labels: priority/normal, status/DNM, status/LGT2, type/enhancement

#163 Imports are organized into groups
  ddl_checker/main.go
Labels: priority/unimportant, status/LGT2

#158 pump client: increase retry time, and refine some code
  checker/main.go
  pkg/diff/diff.go
  pkg/diff/merge.go
  pkg/diff/util.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/watcher/watcher.go
  tidb-binlog/binlogctl/nodes.go
  tidb-binlog/node/registry.go
  tidb-binlog/pump_client/client.go
  tidb-binlog/pump_client/client_test.go
  tidb-binlog/pump_client/pump.go
  tidb-binlog/pump_client/selector.go
Labels: priority/important, status/LGT2, type/bug-fix

#166 fix typos & make golint happy
  pkg/check/binlog.go
  pkg/check/check.go
  pkg/check/privilege.go
  pkg/check/table_structure.go
Labels: Contributor, priority/unimportant, status/LGT1, type/typo

#169 refine dm docs
  docs/dm/zh_CN/README.md
  docs/dm/zh_CN/configuration/configuration.md
  docs/dm/zh_CN/configuration/task.yaml
  docs/dm/zh_CN/dm-worker-unit.md
  docs/dm/zh_CN/get-started.md
  docs/dm/zh_CN/maintenance/dm-ansible.md
  docs/dm/zh_CN/precheck.md
  docs/dm/zh_CN/restrictions.md
  docs/dm/zh_CN/task-handling/task-commands.md
  docs/dm/zh_CN/user-manual.md
Labels: priority/normal, status/LGT2, type/enhancement

#162 check: replace <secret> to 'secret'
  pkg/check/privilege.go
  pkg/check/privilege_test.go
Labels: priority/normal, status/LGT2, type/bug-fix

#165 pump client: add initial log function
  tidb-binlog/pump_client/client.go
  tidb-binlog/pump_client/pump.go
  tidb-binlog/pump_client/selector.go
Labels: priority/normal, status/LGT2, type/log

#170 filter: add `过滤 TiDB parser 不支持的 SQL 语句`
  docs/dm/zh_CN/features/binlog-filter.md
  docs/dm/zh_CN/troubleshoot/skip-replace-sqls.md
Labels: priority/normal, status/LGT2, type/enhancement

#168 adjust a few error messages
  pkg/column-mapping/column.go
Labels: Contributor, priority/unimportant, status/PTAL, type/log

#149 refine binlogctl's output
  tidb-binlog/binlogctl/config.go
  tidb-binlog/binlogctl/nodes.go
Labels: priority/unimportant, status/LGT2, type/log

#173 remove the redundant parentheses & more typos fix
  pkg/dbutil/index.go
  pkg/dbutil/query.go
  pkg/dbutil/table.go
  pkg/ddl-checker/executable_checker.go
Labels: Contributor, status/LGT2

#172 diff: add database name and table name router
  pkg/dbutil/common.go
  sync_diff_inspector/config.go
  sync_diff_inspector/config.toml
  sync_diff_inspector/diff.go
Labels: priority/normal, status/LGT2, type/feature

#175 DM: add DM upgrade guide
  docs/dm/zh_CN/README.md
  docs/dm/zh_CN/maintenance/dm-ansible.md
  docs/dm/zh_CN/upgrade/upgrade-from-loader.md
  docs/dm/zh_CN/upgrade/upgrade-from-syncer.md
  docs/dm/zh_CN/upgrade/upgrade-guide.md
Labels: priority/normal, status/LGT2, type/enhancement

#189 refine binlogctl's output (#149)
  tidb-binlog/binlogctl/config.go
  tidb-binlog/binlogctl/nodes.go
Labels: priority/unimportant, status/LGT1, type/cherry-pick

#179 simplify the if/else logic
  pkg/diff/chunk.go
  pkg/diff/diff.go
  pkg/diff/merge.go
Labels: Contributor, priority/normal, status/LGT2, type/enhancement

#185 Docs
  docs/dm/zh_CN/get-started.md
Labels: priority/unimportant, status/LGT1, type/typo

#130 diff: can use multiple columns to split chunks
  pkg/dbutil/common.go
  pkg/diff/chunk.go
  pkg/diff/chunk_test.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/diff/merge.go
  pkg/diff/util.go
  sync_diff_inspector/config.go
  sync_diff_inspector/config.toml
  sync_diff_inspector/diff.go
Labels: priority/important, status/LGT1, type/enhancement, type/feature

#184 *: remove checker
  Makefile
  README.md
  checker/README.md
  checker/main.go
  ddl_checker/README.md
  tests/checker_integration_test.sh
Labels: priority/normal, status/LGT2, type/enhancement

#167 doc: add document for dm-migrate
  docs/dm/zh_CN/README.md
  docs/dm/zh_CN/maintenance/dm-migrate.md
Labels: priority/normal, status/LGT2, type/log

#191 simplify the if/else logic
  pkg/diff/chunk.go
  pkg/diff/diff.go
Labels: Contributor, priority/normal, status/LGT2

#193 Update Makefile
  Makefile
Labels: priority/normal, status/LGT2, type/enhancement
