Repository pingcap/tidb-tools, pull requests merged in 2019-12, with the labels that each got.

#297 dbutil: update `IsRetryableError`
  go.mod1
  go.sum1
  pkg/dbutil/common.go
  pkg/dbutil/common_test.go
  pkg/dbutil/retry.go
  pkg/dbutil/retry_test.go
Labels: priority/normal, status/LGT2

#296 pkg/etcd: support do some operations in one transaction
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
Labels: priority/normal, status/LGT2

#303 *: update tidb
  go.mod1
  go.sum1
  pkg/dbutil/table.go
  pkg/importer/parser.go
Labels: status/LGT2

#301 restore-util: add method to set placement rules and store labels
  pkg/restore-util/client.go
  pkg/restore-util/split_test.go
Labels: status/WIP

#302 table-rule-selector: add [...] and [!...] wildcard matching
  pkg/table-rule-selector/selector_test.go
  pkg/table-rule-selector/trie_selector.go
Labels: status/LGT2, type/enhancement

#300 restore-util: support batch split
  pkg/restore-util/client.go
  pkg/restore-util/range.go
  pkg/restore-util/split.go
  pkg/restore-util/split_test.go
Labels: status/LGT1

#308 pkg/filter: Add a Match method for checking if a table should be kept
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: status/LGT2

#310 Add unique key info in slave proto
  tidb-binlog/slave_binlog_proto/go-binlog/binlog.pb.go
  tidb-binlog/slave_binlog_proto/proto/binlog.proto
Labels: status/LGT2

#309 .*: update tidb version
  go.mod1
  go.sum1
Labels: priority/normal, status/LGT2
