Repository pingcap/tidb-tools, pull requests merged in 2020-04, with the labels that each got.

#331 diff: escape column name
  pkg/dbutil/common.go
  pkg/dbutil/common_test.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  tests/sync_diff_inspector/run.sh
  tests/sync_diff_inspector/shard/run.sh
Labels: status/LGT2, type/bug-fix

#334 filter/: fix filter panic error
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: status/LGT2

#335 filter: fix caseSensitive not work on match
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: status/LGT2

#337 filter: fix caseSensitive not work on match (#335)
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: status/LGT1

#338 schemacmp: add compatibility for integer and blob
  pkg/schemacmp/lattice.go
  pkg/schemacmp/lattice_test.go
  pkg/schemacmp/table_test.go
  pkg/schemacmp/type.go
  pkg/schemacmp/type_test.go
  pkg/schemacmp/util.go
Labels: priority/normal, status/LGT2, type/enhancement
