Repository pingcap/tidb-tools, pull requests merged in 2020-03, with the labels that each got.

#321 diff: support auto_random in TiDB
  pkg/diff/diff.go
Labels: status/PTAL, type/feature

#322 hard code to remove tidb dep from pkg/filter
  pkg/filter/schema.go
Labels: status/LGT2

#323 pkg: refine tls && update tidb version
  Makefile
  go.mod1
  go.sum1
  pkg/utils/security.go
  pkg/utils/security_test.go
  pkg/utils/tls_test/ca.key
  pkg/utils/tls_test/ca.pem
  pkg/utils/tls_test/client1.key
  pkg/utils/tls_test/client1.pem
  pkg/utils/tls_test/client2.key
  pkg/utils/tls_test/client2.pem
  pkg/utils/tls_test/generate.sh
  pkg/utils/tls_test/server.key
  pkg/utils/tls_test/server.pem
  pkg/utils/util.go
Labels: status/LGT1, type/feature

#324 filter: update metric schema name
  pkg/filter/schema.go
  pkg/filter/schema_test.go
Labels: status/LGT2

#325 schemacmp: properly support PKIsHandle columns
  pkg/schemacmp/table.go
  pkg/schemacmp/table_test.go
Labels: status/LGT2, type/bug-fix

#328 pkg: move tidb error code from the parser/mysql to tidb/errno
  go.mod1
  go.sum1
  pkg/dbutil/retry.go
  pkg/dbutil/retry_test.go
Labels: status/LGT2

#329 pkg: update tls
  pkg/utils/security.go
Labels: status/LGT2
