Repository pingcap/tidb-tools, pull requests merged in 2020-06, with the labels that each got.

#348 make ParseMySQLReplicationRules able to parser nil rules
  pkg/table-filter/compat.go
  pkg/table-filter/compat_test.go
Labels: status/LGT2

#351 Add test for 'exclude-tables' config
  tests/sync_diff_inspector/config_base.toml
  tests/sync_diff_inspector/run.sh
Labels: status/LGT2, type/test

#352 diff: fix block
  pkg/diff/diff.go
Labels: status/LGT2, type/bug-fix

#353 filter,table-filter: replace blacklist/whitelist by blocklist/allowlist
  pkg/filter/filter.go
  pkg/table-filter/README.md
  pkg/table-filter/compat.go
Labels: priority/unimportant, status/LGT2, type/doc

#355 diff: some fix
  go.mod1
  go.sum1
  pkg/dbutil/common.go
  pkg/dbutil/index.go
  pkg/dbutil/table.go
  pkg/dbutil/table_test.go
  pkg/diff/checkpoint.go
  pkg/diff/chunk.go
  pkg/diff/chunk_test.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/importer/importer.go
  pkg/importer/parser.go
  sync_diff_inspector/diff.go
  tests/sync_diff_inspector/run.sh
  tidb-binlog/driver/example/mysql/mysql.go
Labels: status/LGT2

#365 check: remove restrictions for MySQL 8.0
  pkg/check/mysql_server.go
  pkg/check/mysql_server_test.go
  pkg/check/util_test.go
Labels: status/LGT1

#364 diff: refine log
  Makefile
  pkg/dbutil/common.go
  pkg/diff/conn.go
  pkg/utils/printer.go
  sync_diff_inspector/config.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
Labels: status/LGT1, type/log

#366 diff: refine log && minor fix
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/report.go
Labels: status/LGT1, type/bug-fix, type/log

#368 diff: minor fix on integration test
  tests/sync_diff_inspector/ignore_column/run.sh
  tests/sync_diff_inspector/run.sh
  tests/sync_diff_inspector/shard/run.sh
  tests/sync_diff_inspector/snapshot/run.sh
Labels: status/LGT2, type/test
