Repository pingcap/tidb-tools, pull requests merged in 2020-09, with the labels that each got.

#389 gomod: update tidb, parser to latest
  go.mod1
  go.sum1
  pkg/dbutil/common.go
Labels: status/LGT1, status/PTAL

#392 go mod: upgrade tidb/parser/pd to latest release-4.0
  go.mod1
  go.sum1
  pkg/dbutil/common.go
  pkg/ddl-checker/executable_checker.go
Labels: status/PTAL

#393 Revert "gomod: update tidb, parser to latest (#389)"
  go.mod1
  go.sum1
  pkg/dbutil/common.go
Labels: status/LGT2

#394 go mod: update tidb/parser to latest release-4.0
  go.mod1
  go.sum1
  pkg/dbutil/common.go
Labels: status/PTAL

#395 gomod: update tidb, parser to latest (#389)
  go.mod1
  go.sum1
  pkg/dbutil/common.go
Labels: status/LGT1, status/PTAL
