Repository pingcap/tidb-tools, pull requests merged in 2020-05, with the labels that each got.

#342 filter/: fix black white list caseSensitive bug
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: status/PTAL

#343 filter/: fix black white list caseSensitive bug (#342)
  go.mod1
  go.sum1
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/importer/parser.go
Labels: status/LGT1

#341 table-filter: implement the new table filter
  pkg/filter/filter.go
  pkg/table-filter/README.md
  pkg/table-filter/compat.go
  pkg/table-filter/compat_test.go
  pkg/table-filter/filter.go
  pkg/table-filter/filter_test.go
  pkg/table-filter/matchers.go
  pkg/table-filter/parser.go
Labels: priority/normal, status/LGT2, type/feature

#345 diff: fix panic when get empty random value for split chunk
  pkg/diff/chunk.go
  pkg/diff/spliter_test.go
Labels: status/LGT2, type/bug-fix

#346 Two improvements of sync_diff_inspector
  sync_diff_inspector/config.go
  sync_diff_inspector/config.toml
  sync_diff_inspector/diff.go
Labels: status/LGT2

#347 table-filter: added filter.All() to conveniently make a match-all filter
  pkg/table-filter/compat.go
  pkg/table-filter/filter.go
  pkg/table-filter/filter_test.go
Labels: priority/unimportant, status/LGT2, type/enhancement
