Repository pingcap/tidb-tools, pull requests merged in 2020-07, with the labels that each got.

#369 diff: save summary info in memory
  pkg/diff/checkpoint.go
  pkg/diff/checkpoint_test.go
  pkg/diff/chunk.go
  pkg/diff/diff.go
  tests/sync_diff_inspector/run.sh
Labels: status/LGT1

#372 Cherry pick table filters to 3.1
  pkg/filter/filter.go
  pkg/table-filter/README.md
  pkg/table-filter/compat.go
  pkg/table-filter/compat_test.go
  pkg/table-filter/filter.go
  pkg/table-filter/filter_test.go
  pkg/table-filter/matchers.go
  pkg/table-filter/parser.go
Labels: status/LGT2, type/cherry-pick

#373 sync_diff_inspector: fix the snapshot using the DateTime string
  sync_diff_inspector/config.go
Labels: status/LGT1

#374 diff: fix send on closed channel panic
  Makefile
  go.mod1
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  tools.json
Labels: status/LGT2, type/bug-fix

#371 checker: support ANSI_QUOTES
  pkg/check/table_structure.go
Labels: status/LGT2

#370 diff: refine performance and memory usage
  pkg/diff/checkpoint.go
  pkg/diff/checkpoint_test.go
  pkg/diff/chunk.go
  pkg/diff/diff.go
  pkg/diff/merge.go
  sync_diff_inspector/main.go
Labels: status/LGT2, type/enhancement

#376 checker: check primary/unique key exists
  pkg/check/table_structure.go
Labels: status/LGT1

#377 diff: generate check task from dm
  go.mod1
  go.sum1
  sync_diff_inspector/README.md
  sync_diff_inspector/config.go
  sync_diff_inspector/config.toml
  sync_diff_inspector/config_dm.toml
  sync_diff_inspector/config_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/dm.go
  sync_diff_inspector/dm_test.go
Labels: status/LGT2, type/feature

#378 upgrade tidb module, remove deprecated auto random option
  dump_region/main.go
  go.mod1
  go.sum1
  pkg/ddl-checker/executable_checker.go
  pkg/diff/diff.go
  pkg/importer/db.go
  sync_diff_inspector/diff.go
  tools.json
Labels: status/LGT2
