Repository pingcap/tidb-tools, pull requests merged in 2020-08, with the labels that each got.

#380 update slave_binlog to cosumer_binlog
  pkg/dbutil/common.go
  tidb-binlog/driver/example/mysql/mysql.go
  tidb-binlog/driver/reader/offset.go
  tidb-binlog/driver/reader/offset_test.go
  tidb-binlog/driver/reader/reader.go
  tidb-binlog/proto/generate-binlog.sh
  tidb-binlog/proto/go-binlog/binlog.pb.go
  tidb-binlog/proto/proto/binlog.proto
Labels: status/LGT1

#382 table-filter: fix the bug about the table filter parser
  pkg/table-filter/filter_test.go
  pkg/table-filter/parser.go
Labels: status/LGT2

#383 check: support LOAD FROM S3, SELECT INTO S3 for Aurora
  pkg/check/privilege.go
  pkg/check/privilege_test.go
Labels: priority/normal, status/LGT2, type/bug-fix

#386 check: filter NoSuchTableError for checker
  pkg/check/table_structure.go
  pkg/check/util.go
Labels: status/LGT2

#381 check, diff: auto discover ansi-quotes
  pkg/check/table_structure.go
  pkg/dbutil/common.go
  pkg/dbutil/common_test.go
  pkg/dbutil/index_test.go
  pkg/dbutil/table.go
  pkg/dbutil/table_test.go
  pkg/diff/chunk_test.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/diff/merge_test.go
  pkg/diff/spliter_test.go
  pkg/diff/util_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/dm_test.go
  tests/sync_diff_inspector/snapshot/run.sh
Labels: priority/normal, status/LGT2, type/enhancement

#387 check: filter more privilege from AWS
  pkg/check/privilege.go
  pkg/check/privilege_test.go
Labels: status/LGT1
