Repository pingcap/tidb-tools, pull requests merged in 2021-08, with the labels that each got.

#468 refine source for mysql/TiDB
  sync_diff_inspector/config/config.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/basic.go
  sync_diff_inspector/source/common/rows.go
  sync_diff_inspector/source/mysql.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/splitter.go
Labels: size/XXL

#463 Diff 2.0: impl bingenerate
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/basic.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: first-time-contributor, size/XL

#470 Implement Mysql shard source
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/basic.go
  sync_diff_inspector/source/common/rows.go
  sync_diff_inspector/source/common/table_diff.go
  sync_diff_inspector/source/mysql.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/utils/utils.go
Labels: size/XL

#471 Diff 2.0: impl config hash
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/basic.go
  sync_diff_inspector/source/common/table_diff.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
Labels: first-time-contributor, size/L

#469 diff2: add test
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/chunk/chunk_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/basic.go
  sync_diff_inspector/source/common/common_test.go
  sync_diff_inspector/source/mysql.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter.go
  sync_diff_inspector/splitter/splitter_test.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: first-time-contributor, size/XXL

#474 Diff2: fix bug
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/common/table_diff.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/splitter/bucket.go
Labels: first-time-contributor, size/S

#475 Diff2: fix bug
  sync_diff_inspector/diff.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/utils/utils.go
Labels: size/L, first-time-contributor

#476 Diff 2.0: debug
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/basic.go
  sync_diff_inspector/splitter/splitter.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: size/M, first-time-contributor

#477 Diff2: fix bugs
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
Labels: size/L, first-time-contributor

#478 Add router for different Source.
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/basic.go
  sync_diff_inspector/source/common/rows.go
  sync_diff_inspector/source/common/table_diff.go
  sync_diff_inspector/source/mysql.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/utils/utils.go
Labels: size/XL

#479 refine some code && fix db connection
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/mysql.go
  sync_diff_inspector/source/tidb.go
Labels: size/S

#480 Diff 2.0： fix bug
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/basic.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter.go
  sync_diff_inspector/splitter/splitter_test.go
Labels: size/M, first-time-contributor

#481 Diff2: add limit splitter and fix some bugs
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/source/mysql.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/limit.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter_test.go
Labels: size/XL, first-time-contributor

#482 Refine config
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/config/config.go
  sync_diff_inspector/config/config.toml
  sync_diff_inspector/config/config_sharding.toml
  sync_diff_inspector/config/config_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/basic.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/utils/utils.go
Labels: size/XXL

#485 Diff 2.0: impl summary
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/config/config.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/report.go
  sync_diff_inspector/source/basic.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/limit.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: first-time-contributor, size/XXL

#484 put mysql and mysql_shard together
  sync_diff_inspector/config/config.go
  sync_diff_inspector/config/config_sharding.toml
  sync_diff_inspector/config/config_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/source/chunks_iter.go
  sync_diff_inspector/source/mysql.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
Labels: size/XXL

#486 Diff2：add SQL info and float support.
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/basic.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/utils/utils.go
Labels: size/L, first-time-contributor

#487 diff: Remove useless code
  go.mod1
  go.sum1
  sync_diff_inspector/source/basic.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/utils/utils.go
Labels: size/XL

#488 Impl report
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/config/config.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/report/report.go
  sync_diff_inspector/source/common/table_diff.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/limit.go
  sync_diff_inspector/utils/utils.go
Labels: size/L, first-time-contributor

#490 format code
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/report/report.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/tidb.go
Labels: size/L

#492 Diff2: add progress bar
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/chunk/chunk_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/progress/progress.go
  sync_diff_inspector/progress/progress_test.go
  sync_diff_inspector/source/chunks_iter.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/limit.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter.go
  sync_diff_inspector/splitter/splitter_test.go
  sync_diff_inspector/utils/utils.go
Labels: first-time-contributor, size/XXL

#491 support GC safepoint keepper
  go.mod1
  sync_diff_inspector/diff.go
  sync_diff_inspector/utils/pd.go
Labels: size/XL

#493 diff2: add unit_test
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/chunk/chunk_test.go
  sync_diff_inspector/config/config.go
  sync_diff_inspector/config/config_sharding.toml
  sync_diff_inspector/config/config_test.go
  sync_diff_inspector/config/dm/dm.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/report/report.go
  sync_diff_inspector/report/report_test.go
  sync_diff_inspector/source/common/common_test.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/limit.go
  sync_diff_inspector/splitter/splitter_test.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: first-time-contributor, size/XXL
