Repository pingcap/tidb-tools, pull requests merged in 2021-10, with the labels that each got.

#526 Diff2：simplify the where of chunk when the upper and lower of the previous columns in sequence are the same.
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/chunk/chunk_test.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: status/LGT1, size/L, first-time-contributor

#531 Diff2: update config
  sync_diff_inspector/config/config.go
  sync_diff_inspector/config/config.toml
  sync_diff_inspector/config/config_sharding.toml
  sync_diff_inspector/config/config_test.go
  sync_diff_inspector/main.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/splitter/bucket.go
  tests/sync_diff_inspector/checkpoint/config_base.toml
  tests/sync_diff_inspector/checkpoint/config_base_continous.toml
  tests/sync_diff_inspector/checkpoint/config_base_rand.toml
  tests/sync_diff_inspector/config_base_mysql.toml
  tests/sync_diff_inspector/config_base_tidb.toml
  tests/sync_diff_inspector/shard/config_base.toml
  tests/sync_diff_inspector/snapshot/config_base.toml
  tests/sync_diff_inspector/table_config/config.toml
  tests/sync_diff_inspector/time_zone/config.toml
Labels: status/LGT1, size/M, first-time-contributor

#528 table-filter: add column filter
  pkg/table-filter/column_filter.go
  pkg/table-filter/column_filter_test.go
  pkg/table-filter/compat.go
  pkg/table-filter/helper.go
  pkg/table-filter/matchers.go
  pkg/table-filter/parser.go
  pkg/table-filter/table_filter.go
  pkg/table-filter/table_filter_test.go
Labels: status/LGT1, status/can-merge, size/XXL
