Repository pingcap/tidb-tools, pull requests merged in 2021-12, with the labels that each got.

#562 *: update dep to ticdc
  go.mod1
  go.sum1
  sync_diff_inspector/config/dm.go
Labels: status/LGT1, status/can-merge, size/XL

#560 fix max-index-length
  sync_diff_inspector/diff.go
Labels: status/LGT1, status/can-merge, size/XS

#569 *: update dep to tiflow
  go.mod1
  go.sum1
  sync_diff_inspector/config/dm.go
Labels: status/LGT1, size/M, status/can-merge

#573 sync-diff: fix ci test: gbk and structure compare result
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: status/LGT1, status/can-merge, size/S

#568 add issue requirement to pull request template
  .github/pull_request_template.md
Labels: status/LGT1, status/can-merge, size/S

#576 sync_diff: index compare result impact the result of table struct compare
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: status/LGT1, status/can-merge, size/XS

#574 sync_diff: rows_scan_float_keep_6_digits
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: status/LGT1, status/can-merge, size/S

#578 Sync go:build lines
  pkg/utils/cpu_posix.go
  pkg/utils/cpu_windows.go
Labels: status/LGT1, status/can-merge, first-time-contributor, size/XS
