Repository pingcap/tidb-tools, pull requests merged in 2021-07, with the labels that each got.

#452 add ErrTxnRetryable to retry error
  pkg/dbutil/retry.go
  pkg/dbutil/retry_test.go
Labels: size/XS, status/LGT1, status/can-merge

#454 impl checkpoint
  sync_diff_inspector/checkpoints.go
  sync_diff_inspector/checkpoints_test.go
  sync_diff_inspector/diff.go
Labels: first-time-contributor, size/L

#453 Diff2: change iterator interface
  sync_diff_inspector/checkpoints.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter.go
  sync_diff_inspector/utils/utils.go
Labels: first-time-contributor, size/L, status/LGT1

#457 diff2: add random and bucket splitter.
  sync_diff_inspector/checkpoints.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter.go
Labels: first-time-contributor, size/XL

#456 abstract sql.DB to interface
  pkg/check/table_structure.go
  pkg/dbutil/common.go
  pkg/dbutil/index.go
  pkg/dbutil/interface.go
  pkg/dbutil/table.go
  pkg/dbutil/variable.go
Labels: size/L, status/LGT1, status/can-merge

#455 Diff 2.0
  sync_diff_inspector/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/common/table_diff.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
Labels: first-time-contributor, size/XXL, status/LGT1

#458 security: support init tls config from cert/key/ca bytes
  go.sum1
  pkg/utils/security.go
  pkg/utils/security_test.go
Labels: size/M, status/LGT1, status/can-merge

#459 diff2: chunksIter checkpoints
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/utils/utils.go
Labels: first-time-contributor, size/XXL, status/LGT1

#460 Diff 2.0
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
Labels: first-time-contributor, size/L

#461 Diff2: init tables
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/mysql.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/utils/utils.go
Labels: first-time-contributor, size/XL

#462 Refactor && optimize diff 2.0
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/utils/utils.go
Labels: size/XL

#464 refine checkpoint node logic
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
Labels: size/XL

#466 split rangeInfo from Node
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter.go
Labels: size/L

#467 Resolve some todo
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter.go
Labels: size/L
