Repository pingcap/tidb-tools, pull requests merged in 2021-04, with the labels that each got.

#429 schemacmp: skip empty charset and collate in table.String()
  pkg/schemacmp/table.go
  pkg/schemacmp/table_test.go
Labels: size/M, status/LGT1, status/can-merge

#430 check: pretty print the checker errors
  pkg/check/binlog.go
  pkg/check/check.go
  pkg/check/mysql_server.go
  pkg/check/privilege.go
  pkg/check/table_structure.go
  pkg/check/table_structure_test.go
  pkg/check/util.go
Labels: size/XL, status/LGT1, status/can-merge

#432 dbutil: fix can't handle masked password in SHOW GRANTS
  pkg/check/privilege.go
  pkg/check/privilege_test.go
  pkg/dbutil/variable.go
  pkg/dbutil/variable_test.go
Labels: size/L, status/LGT1, status/can-merge
