Repository pingcap/tidb-tools, pull requests merged in 2021-11, with the labels that each got.

#541 Rename binlog proto
  tidb-binlog/driver/example/kafkaReader/README.md
  tidb-binlog/proto/generate-binlog.sh
  tidb-binlog/proto/go-binlog/secondary_binlog.pb.go
  tidb-binlog/proto/proto/secondary_binlog.proto
Labels: status/LGT1, status/can-merge, size/XL

#542 sync_diff_inspector: do exit(2) when exist error
  sync_diff_inspector/main.go
Labels: status/LGT1, status/can-merge, size/XS

#520 support table transfer column for dm
  pkg/table-router/router.go
  pkg/table-router/router_test.go
Labels: status/LGT1, status/can-merge, size/L, first-time-contributor, contribution

#543 sync_diff_inspector: Unified time zone
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/common/table_diff.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/splitter_test.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
  tests/sync_diff_inspector/time_zone/run.sh
Labels: status/LGT1, status/can-merge, size/L

#544 sync-diff-inspector: optimize CountAndChecksum
  sync_diff_inspector/utils/utils.go
Labels: status/LGT1, status/can-merge, size/XS

#549 sync-diff: Fix Down Stream Reference
  sync_diff_inspector/utils/utils.go
Labels: status/LGT1, status/can-merge, first-time-contributor, size/XS, contribution

#550 fix links in sync_diff_inspector readme
  sync_diff_inspector/README.md
Labels: status/LGT1, status/can-merge, first-time-contributor, size/XS, contribution

#555 sync-diff-inspector: add docs link
  sync_diff_inspector/README.md
  sync_diff_inspector/main.go
Labels: status/LGT1, status/can-merge, size/XS
