Repository pingcap/tidb-tools, pull requests merged in 2021-06, with the labels that each got.

#441 filter: add another Apply function for filter to return the original value
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: size/L, status/LGT1, status/can-merge

#442 sync-diff: fix the problem that sync diff data is null
  pkg/dbutil/common.go
  pkg/diff/diff.go
Labels: size/S, status/LGT1, status/can-merge

#444 *: Clear redundant log methods
  pkg/ddl-checker/executable_checker.go
  tidb-binlog/pump_client/client.go
Labels: first-time-contributor, size/XS, status/LGT1, status/can-merge

#446 sync_diff_inspector: fix a index of range panic
  pkg/diff/chunk.go
Labels: size/XS, status/LGT1, status/can-merge
