Repository pingcap/tidb-tools, pull requests merged in 2021-09, with the labels that each got.

#494 update the policy of chunk count.
  sync_diff_inspector/config/config.go
  sync_diff_inspector/config/config_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/source/common/table_diff.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/limit.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter.go
  sync_diff_inspector/splitter/splitter_test.go
  sync_diff_inspector/utils/pd.go
  sync_diff_inspector/utils/utils.go
Labels: size/L

#496 Fix checkpoint
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/report/report.go
  sync_diff_inspector/report/report_test.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/utils/utils.go
Labels: size/XL, first-time-contributor

#498 use the upsteam info as base compare result
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
Labels: size/M

#500 concurrent produce chunks for bucket iterator
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/splitter_test.go
  sync_diff_inspector/utils/utils_test.go
Labels: size/XL

#501 fix compare Chunk bounds
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/chunk/chunk_test.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
Labels: size/L

#502 Diff2: add unit test coverage
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/config/config_test.go
  sync_diff_inspector/progress/progress.go
  sync_diff_inspector/progress/progress_test.go
  sync_diff_inspector/report/report.go
  sync_diff_inspector/report/report_test.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/splitter/splitter_test.go
  sync_diff_inspector/utils/utils_test.go
Labels: first-time-contributor, size/XXL

#503 Diff 2.0
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/chunk/chunk_test.go
  sync_diff_inspector/source/chunks_iter.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
Labels: size/L, first-time-contributor

#504 Diff2: fix unit test and bucket checkpoint
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/chunk/chunk_test.go
  sync_diff_inspector/source/chunks_iter.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/limit.go
  sync_diff_inspector/splitter/random.go
Labels: status/LGT1, size/L, first-time-contributor

#505 Diff 2.0
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/chunk/chunk_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/report/report.go
  sync_diff_inspector/report/report_test.go
  sync_diff_inspector/source/chunks_iter.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/splitter/splitter.go
  sync_diff_inspector/splitter/splitter_test.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: size/XL, first-time-contributor

#506 Diff2: add checkpoint integration test
  .gitignore
  Makefile
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/chunk/chunk_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/report/report_test.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/limit.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter.go
  sync_diff_inspector/splitter/splitter_test.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
  tests/run.sh
  tests/sync_diff_inspector/checkpoint/config_base.toml
  tests/sync_diff_inspector/checkpoint/run.sh
  tools.json
  tools/.gitignore
  tools/Makefile
  tools/go.mod
  tools/go.sum
  tools/go_mod_guard.go
Labels: first-time-contributor, size/XXL

#508 Diff 2.0: impl produceChunkIter
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/source/chunks_iter.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/utils/utils.go
Labels: size/L, first-time-contributor

#507 Diff2: fix splitter checkpoint and add unit/integration test
  sync_diff_inspector/chunk/chunk_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter_test.go
  sync_diff_inspector/utils/utils_test.go
  tests/_utils/check_contains_regex
  tests/sync_diff_inspector/checkpoint/config_base_rand.toml
  tests/sync_diff_inspector/checkpoint/run.sh
Labels: first-time-contributor, size/XXL

#509 Diff2: add global channel for chunks_iter to generate chunks smoothly
  sync_diff_inspector/source/chunks_iter.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/splitter_test.go
Labels: size/L, first-time-contributor

#512 Diff2: progress bar support load checkpoint
  sync_diff_inspector/diff.go
  sync_diff_inspector/progress/progress.go
  sync_diff_inspector/progress/progress_test.go
Labels: size/L, first-time-contributor

#511 Diff 2.0: fix checkpoint
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff.go
Labels: size/M, first-time-contributor

#514 Diff2: add annontation and optimization
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/chunk/chunk_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/progress/progress.go
  sync_diff_inspector/source/chunks_iter.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/limit.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter_test.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: size/XL, first-time-contributor

#515 Diff 2.0
  sync_diff_inspector/diff.go
Labels: first-time-contributor

#516 Diff2: handle some errors and add annotation
  Makefile
  sync_diff_inspector/config/config.toml
  sync_diff_inspector/config/config_sharding.toml
  sync_diff_inspector/report/report.go
  sync_diff_inspector/source/chunks_iter.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: size/L, first-time-contributor

#518 Diff 2.0: delete rowCnt
  sync_diff_inspector/diff.go
  sync_diff_inspector/report/report.go
  sync_diff_inspector/report/report_test.go
Labels: status/LGT1, size/M, first-time-contributor

#517 Diff2: delete useless variable `bucket-id`
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/checkpoints/checkpoints_test.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/chunk/chunk_test.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/splitter.go
Labels: size/M, first-time-contributor

#519 Diff2: fix some typos and handle checksum error
  sync_diff_inspector/config/config.go
  sync_diff_inspector/config/config.toml
  sync_diff_inspector/config/config_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/progress/progress.go
  sync_diff_inspector/report/report.go
  sync_diff_inspector/report/report_test.go
  sync_diff_inspector/source/source_test.go
Labels: status/LGT1, size/L, first-time-contributor
