Repository pingcap/tidb-tools, pull requests merged in 2022-03, with the labels that each got.

#597 sync-diff: turn off new collation
  pkg/dbutil/table.go
  pkg/dbutil/table_test.go
Labels: status/LGT1, size/M, status/can-merge

#601 router: regular expression compatible router for DM and Lightning
  pkg/regexpr-router/regexpr_router.go
  pkg/regexpr-router/regexpr_router_test.go
Labels: status/LGT1, status/can-merge, size/XXL

#602 remove ddl dependency
  go.mod1
  go.sum1
  pkg/dbutil/common.go
  tools/go.mod
  tools/go.sum
Labels: status/LGT1, status/can-merge, size/L

#605 *: set min tls version to tls1.0
  pkg/utils/security.go
Labels: status/LGT1, status/can-merge, size/XS

#607 dep: update TiDB and parser
  go.mod1
  go.sum1
  pkg/dbutil/common.go
Labels: status/LGT1, status/can-merge, size/L
