Repository pingcap/tidb-tools, pull requests merged in 2022-09, with the labels that each got.

#673 upgrade to go 1.19
  go.mod1
  go.sum1
  pkg/binlog-filter/filter.go
  pkg/table-rule-selector/trie_selector.go
  pkg/utils/errors.go
  pkg/watcher/watcher.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/config/dm.go
  sync_diff_inspector/utils/utils.go
Labels: status/LGT1, status/can-merge, size/XXL

#674 sync_diff: support json compare
  sync_diff_inspector/diff.go
  sync_diff_inspector/utils/utils.go
Labels: status/LGT1, status/can-merge, size/S

#675 sync-diff-inspector: support tls for sync-diff-inspector
  go.mod1
  go.sum1
  sync_diff_inspector/config/config.go
  sync_diff_inspector/config/config.toml
  sync_diff_inspector/config/config_test.go
  sync_diff_inspector/config/dm.go
  sync_diff_inspector/config/template.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/common/conn.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/utils/utils.go
  tests/conf/client.crt
  tests/conf/client.key
  tests/conf/root.crt
  tests/conf/tidb.crt
  tests/conf/tidb.key
  tests/run.sh
  tests/sync_diff_inspector/json/config_base.toml
  tests/sync_diff_inspector/json/data.sql
  tests/sync_diff_inspector/json/run.sh
  tests/sync_diff_inspector/tls/config.toml
  tests/sync_diff_inspector/tls/run.sh
Labels: status/LGT1, status/can-merge, size/XXL

#679 sync-diff-inspector: add annotation for create table info
  pkg/dbutil/table.go
  pkg/dbutil/table_test.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/utils/pd.go
Labels: status/LGT1, status/can-merge, size/L

#681 sync-diff-inspector: fix rows unclosed
  pkg/dbutil/table.go
Labels: status/LGT1, status/can-merge, size/XS
