Repository pingcap/tidb-tools, pull requests merged in 2022-07, with the labels that each got.

#655 binlog-filter: add new event type
  pkg/binlog-filter/filter.go
  pkg/binlog-filter/filter_test.go
  pkg/binlog-filter/util.go
Labels: status/LGT1, status/can-merge, size/L

#658 binlog_filter: add 'AlterDatabase' and 'AlterSchema' to ClassifyEvent.
  pkg/binlog-filter/filter.go
  pkg/binlog-filter/filter_test.go
Labels: status/LGT1, size/M, status/can-merge

#633 remove pkg/table-router and invoke tidb/util/table-router
  go.mod1
  go.sum1
  pkg/regexpr-router/regexpr_router.go
  pkg/regexpr-router/regexpr_router_test.go
  pkg/table-router/router.go
  pkg/table-router/router_test.go
  sync_diff_inspector/config/config.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
Labels: status/LGT1, status/can-merge, size/XXL

#659 binlog-filter: add new event types.
  pkg/binlog-filter/filter.go
  pkg/binlog-filter/filter_test.go
  pkg/binlog-filter/util.go
Labels: status/LGT1, status/can-merge, size/S
