Repository pingcap/tidb-tools, pull requests merged in 2022-08, with the labels that each got.

#668 tidb-binlog: archive tidb-binlog directory
  tidb-binlog/README.md
  tidb-binlog/driver/README.md
  tidb-binlog/driver/example/kafkaReader/.gitignore
  tidb-binlog/driver/example/kafkaReader/README.md
  tidb-binlog/driver/example/kafkaReader/pom.xml
  tidb-binlog/driver/example/kafkaReader/src/main/java/Booter.java
  tidb-binlog/driver/example/kafkaReader/src/main/java/com/pingcap/kafkareader/proto/BinLogInfo.java
  tidb-binlog/driver/example/kafkaReader/src/main/java/com/pingcap/kafkareader/proto/DescriptorProtos.java
  tidb-binlog/driver/example/kafkaReader/src/main/java/com/pingcap/kafkareader/proto/GoGoProtos.java
  tidb-binlog/driver/example/kafkaReader/src/main/resources/proto/binlog.proto
  tidb-binlog/driver/example/kafkaReader/src/main/resources/proto/descriptor.proto
  tidb-binlog/driver/example/kafkaReader/src/main/resources/proto/gogo.proto
  tidb-binlog/driver/example/mysql/mysql.go
  tidb-binlog/driver/example/print/print.go
  tidb-binlog/driver/reader/offset.go
  tidb-binlog/driver/reader/offset_test.go
  tidb-binlog/driver/reader/reader.go
  tidb-binlog/node/node.go
  tidb-binlog/node/registry.go
  tidb-binlog/node/registry_test.go
  tidb-binlog/proto/generate-binlog.sh
  tidb-binlog/proto/go-binlog/secondary_binlog.pb.go
  tidb-binlog/proto/proto/secondary_binlog.proto
  tidb-binlog/pump_client/bench_test.go
  tidb-binlog/pump_client/client.go
  tidb-binlog/pump_client/client_test.go
  tidb-binlog/pump_client/pump.go
  tidb-binlog/pump_client/selector.go
Labels: status/LGT1, status/can-merge, size/XXL

#664 sync_diff_inspector: add auto-position of tidb_snapshot
  sync_diff_inspector/config/config.go
  sync_diff_inspector/config/config.toml
  sync_diff_inspector/source/source.go
Labels: status/LGT1, size/M, status/can-merge, first-time-contributor

#630 sync_diff_inspector: add config item: chunk-thread-count
  sync_diff_inspector/README.md
  sync_diff_inspector/config/config.go
  sync_diff_inspector/config/config_test.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/chunks_iter.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/splitter_test.go
Labels: status/LGT1, status/can-merge, size/L

#547 sync-diff-inspector: Clear some codes and optimize GetRandomValues
  sync_diff_inspector/config/config.go
  sync_diff_inspector/diff.go
  sync_diff_inspector/main.go
  sync_diff_inspector/source/chunks_iter.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/limit.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter_test.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: status/LGT1, status/can-merge, size/L

#628 dbutil: add `interpolateParams=true` into DSN
  pkg/dbutil/common.go
  sync_diff_inspector/source/common/conn.go
  sync_diff_inspector/source/source.go
Labels: status/LGT1, size/M, status/can-merge
