Repository pingcap/tidb-tools, pull requests merged in 2022-04, with the labels that each got.

#610 filter sequence
  pkg/dbutil/common.go
Labels: status/LGT1, status/can-merge, size/XS

#611 sync-diff: make sure user setting can cover the default same table route rules
  sync_diff_inspector/config/config.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  tests/_utils/check_contains_count
  tests/sync_diff_inspector/shard/config_router_1.toml
  tests/sync_diff_inspector/shard/config_router_2.toml
  tests/sync_diff_inspector/shard/config_router_3.toml
  tests/sync_diff_inspector/shard/config_router_4.toml
  tests/sync_diff_inspector/shard/config_router_5.toml
  tests/sync_diff_inspector/shard/run.sh
Labels: status/LGT1, status/can-merge, size/XXL

#614 sync_diff_inspector: Table range should be FALSE when all the columns are equal
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/chunk/chunk_test.go
  sync_diff_inspector/diff.go
Labels: status/LGT1, size/M, status/can-merge
