Repository pingcap/tidb-tools, pull requests merged in 2022-01, with the labels that each got.

#582 sync_diff_inspector: check column length
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: status/LGT1, size/M, status/can-merge

#580 Improve handling of output-dir
  sync_diff_inspector/config/config.go
  sync_diff_inspector/diff.go
Labels: status/LGT1, status/can-merge, first-time-contributor, size/XS

#586 sync_diff: fix chunkSize is 0 when table is empty
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter_test.go
Labels: status/LGT1, status/can-merge, size/XS

#557 sync-diff-inspector: fix report error panic
  sync_diff_inspector/report/report.go
  sync_diff_inspector/report/report_test.go
Labels: status/LGT1, status/can-merge, size/S

#548 sync-diff: add table match check
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: status/LGT1, status/can-merge, size/L

#553 sync-diff-inspector: add default outputDir and support to export the template config
  sync_diff_inspector/config/config.go
  sync_diff_inspector/config/template.go
  sync_diff_inspector/main.go
Labels: status/LGT1, status/can-merge, size/L

#554 sync-diff-inspector: record downstream count in the report
  sync_diff_inspector/diff.go
  sync_diff_inspector/report/report.go
  sync_diff_inspector/report/report_test.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: status/LGT1, status/can-merge, size/L
