Repository pingcap/tidb-tools, pull requests merged in 2023-03, with the labels that each got.

#700 sync_diff_inspector: fix return err when float/double is zero
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: status/LGT1, size/M, status/can-merge, first-time-contributor, contribution

#708 sync_diff_inspector: fix float degree
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: status/LGT1, status/can-merge, size/S

#715 feat(json): fix hidden column make by json
  sync_diff_inspector/utils/utils.go
Labels: status/LGT1, status/can-merge, size/XS, do-not-merge/needs-linked-issue

#714 sync-diff: update DM dependency
  go.mod1
  go.sum1
  sync_diff_inspector/config/config.go
  sync_diff_inspector/config/dm_test.go
Labels: status/LGT1, status/can-merge, size/XL, skip-issue-check
