Repository pingcap/tidb-tools, pull requests merged in 2024-08, with the labels that each got.

#809 sync_diff_inspector: show hex data for binary column
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/utils/utils.go
Labels: size/M, lgtm, approved

#810 *: improve security
  pkg/check/privilege.go
  pkg/dbutil/variable.go
  pkg/dbutil/variable_test.go
  pkg/ddl-checker/executable_checker.go
  pkg/diff/checkpoint.go
  pkg/diff/checkpoint_test.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
Labels: size/M, lgtm, approved, release-note

#787 Use md5 checksum instead of crc32
  sync_diff_inspector/diff.go
  sync_diff_inspector/source/mysql_shard.go
  sync_diff_inspector/source/source.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/source/tidb.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: size/M, first-time-contributor, contribution, lgtm, approved, release-note-none, ok-to-test
