Repository pingcap/tidb-tools, pull requests merged in 2024-05, with the labels that each got.

#783 build: Upgrade tidb dependency
  go.mod
  go.mod1
  go.sum
  sync_diff_inspector/source/source_test.go
Labels: first-time-contributor, size/XXL, lgtm, approved, release-note-none

#786 Support DML generation for blob data
  pkg/dbutil/types.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
Labels: size/L, first-time-contributor, contribution, lgtm, approved, release-note-none

#788 update tiflow version
  go.mod
  go.sum
Labels: size/L, lgtm, approved, release-note-none

#793 sync_diff_inspector: Improve startup errors
  sync_diff_inspector/main.go
Labels: size/XS, lgtm, approved, release-note-none

#791 Update description for -T
  sync_diff_inspector/README.md
  sync_diff_inspector/config/config.go
Labels: size/S, lgtm, approved, release-note-none

#796 sync-diff-inspector: Fix double quoting
  sync_diff_inspector/progress/progress.go
  sync_diff_inspector/progress/progress_test.go
  tests/sync_diff_inspector/table_skip/run.sh
Labels: size/M, lgtm, approved, release-note-none

#778 sync-diff-inspector: fix typo
  sync_diff_inspector/report/report.go
  sync_diff_inspector/report/report_test.go
Labels: first-time-contributor, size/S, skip-issue-check, lgtm, approved, release-note-none

#798 sync-diff-inspector: Cleanup Trash
  sync_diff_inspector/diff.go
Labels: size/XS, lgtm, approved, release-note-none

#800 sync-diff-inspector: Fix confusing version output
  sync_diff_inspector/main.go
Labels: size/XS, lgtm, approved, release-note-none
