Repository pingcap/tidb-tools, pull requests merged in 2024-01, with the labels that each got.

#765 integration_test: use dumpling to replace mydumper
  Makefile
  importer/README.md
  tests/README.md
  tests/sync_diff_inspector/run.sh
Labels: size/XS, lgtm, approved, release-note-none

#766 add binlog filter ddl event type
  pkg/binlog-filter/filter.go
  pkg/binlog-filter/util.go
Labels: size/M, lgtm, approved, release-note-none

#772 filter: add more event types to ClassifyEvent
  pkg/binlog-filter/filter.go
Labels: size/S, lgtm, approved, release-note-none
